### ISSUE TITLE
Ability to use --get-volume and --get-mute at the same time

### ISSUE THREAD

**Issue by Bew78LesellB** [cdemoulins/pamixer#12]
Thanks for your work it's awesome when `pactl` doesn't allow you to easily get the volume for example !

It could reply something like `[status] percentage` or just `status percentage` to easily parse the response in a script.

I have a script that (always) use asynchronous call to get the response, and it would be easier to get _status_ and _percentage_ at the same call..

I've seen that the 2 options are in the list of conflicting options, why ?

Thank's for reading

**Comment by cdemoulins** [comment]
Sorry for the delay.
What do you mean by status ? Mute status ?

**Comment by Bew78LesellB** [comment]
Sorry for the delay (mine was a little bigger imo)

Yes exactly, so I can get all audio status in one command!

**Comment by cdemoulins** [comment]
Done
