### ISSUE TITLE
Feature Request: Microphone mute functionality

### ISSUE THREAD

**Issue by drewofdoom** [cdemoulins/pamixer#23]
I use pamixer in conjunction with a tiling window manager using keybinds to issue commands. My laptop has a microphone mute button that I would love to be able to trigger using this utility. Is there any chance you would add the ability to toggle source mutes in addition to sink mutes?

**Comment by roryrjb** [comment]
You can already do this. There isn't a single built in command necessarily, but I have written a script that I use to toggle all sources (just ignore the notify stuff):

```bash
#!/bin/sh

notify=

while [ $# -gt 0 ]; do
    case $1 in
        --notify) notify=1 ;;
        *) true ;;
    esac

    shift
done

if ! command -v pamixer > /dev/null; then
    exit_code="$?"

    if [ "$notify" ]; then
        notify-send \
            --hint=int:transient:1 \
            "Error" \
            "'pamixer' is not available."
    fi

    exit $exit_code
fi

pamixer --list-sources \
    | grep input \
    | awk '{print $1}' \
    | while read -r index; do
    mic_muted="$(pamixer --source "$index" --get-mute)"

    if [ "$mic_muted" = "true" ]; then
        pamixer --source "$index" -u
    else
        pamixer --source "$index" -m
    fi

    if [ "$notify" ]; then
        notify-send --hint=int:transient:1 "Mic Toggle" "Toggled"
    fi
done
```
(https://git.sr.ht/~roryrjb/home/tree/master/bin/Linux/mic_toggle)

**Comment by erazemkokot** [comment]
@drewofdoom I think the command `pamixer --default-source -t` does what you want.
