### ISSUE TITLE
Suggestion: update README to be more specific on the dependencies.

### ISSUE THREAD

**Issue by scott092707** [cdemoulins/pamixer#30]
README.rst lists:
"Dependencies
libpulse
boost-program_options"

I already had libpulse0, and after I installed libboost-program-options1.71.0, I thought all would be good.
No.

Eventually, I found I had to install libpulse-dev and libboost-program-options1.71-dev .

Indicating that -dev packages are required, and that the boost package was a library ("lib-") would save a bit of confusion
(at least for those of us less savvy about compilation)...

--------------------------------------
[Incidentally - I have to assume that boost really helps your software development, since to compile your 369KB program:
-rwxr-xr-x 1 scott scott 369200 Aug  3 17:54 pamixer
One needs to install 142MB of boost-related files
"After this operation, 142 MB of additional disk space will be used." , since  libboost-program-options1.71-dev (3.7MB) pulls in 
libboost1.71-dev (138MB) as well...
(and also libboost-program-options1.71.0 (2.6MB), which I had already installed in my attempts to make pamixer).]

**Comment by cdemoulins** [comment]
"-dev" dependencies are Debian specific. I can add that you need the headers of this libraries if you want.
