### ISSUE TITLE
Add playing of sound when volume changes

### ISSUE THREAD

**Issue by norpol** [cdemoulins/pamixer#35]
I'm not sure whether this makes sense to add into pamixer given it's not running in a daemon mode. But looking at how pavucontrol has added a sound when you change a devices volume makes me think adding this to pamixer might not be as hard since the underlying code already exists.

https://github.com/pulseaudio/pavucontrol/commit/8a11d0f781c283c26942f7cb02fa733df79ff731#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810L40-L42

is the latest commit that touches that code and might give some insight in how this is implemented.

Basically it uses libcanberra [ `CA_PROP_EVENT_ID`](http://0pointer.de/lennart/projects/libcanberra/gtkdoc/libcanberra-canberra.html#CA-PROP-EVENT-ID:CAPS) to play `audio-volume-change` which uses the systems installed Freedesktop [sound-theme](https://freedesktop.org/wiki/Specifications/sound-theme-spec/) files.

Though in pavucontrol it replaces currently playing audio-volume-change sound whenever a new volume change event is incoming, I'm not sure how well this would work with pamixer - so I guess I might just end up writing a daemon-wrapper around pamixer to allow such functionality.

Time being I'm just using `canberra-gtk-play --id=audio-volume-change` in my pamixer wrapper.

**Comment by cdemoulins** [comment]
I don't want to add a dependency gtk just for that sorry. pavucontrol is already using it so it's easy to add another gtk dependency.
