### ISSUE TITLE
pthread_mutex_destroy Assertion failure on exit

### ISSUE THREAD

**Issue by eankeen** [cdemoulins/pamixer#37]
After opening pamixer and using normally, I receive an error on exit, after pressing `q`

```sh
> pamix
Assertion 'pthread_mutex_destroy(&m->mutex) == 0' failed at ../pulseaudio/src/pulsecore/mutex-posix.c:83, function pa_mutex_free(). Aborting.
Aborted (core dumped)
```

This occurs even if I close right after I open it. Sometimes, the volume drops to 10%.

**Comment by cdemoulins** [comment]
pamix != pamixer

https://github.com/patroclos/PAmix
