### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by nichobi** [cdemoulins/pamixer#39]
It's been a couple of years since the last release and a number of useful features have been added:
* #18 
* #36 
* #21 

Would be nice to see these included in a `1.5` release tag, so they can be included in package repos.

**Comment by thiagokokada** [comment]
@cdemoulins Could you consider making a new tag?

I am bumping this package on https://github.com/NixOS/nixpkgs/pull/139961. While they generally accept building from master, it is easier to get proper releases to be merged.

**Comment by cdemoulins** [comment]
I will add the --version option and release the tag 1.5.
