### ISSUE TITLE
Add sleep when polling state?

### ISSUE THREAD

**Issue by beaumanvienna** [cdemoulins/pamixer#43]
Have you considered putting a sleep instruction [here](https://github.com/cdemoulins/pamixer/blob/298495d15d08a0169f2144391c0d47826aafa151/pulseaudio.cc#L33) when you're polling the state to prevent the CPU from running at 100% when the pulse audio demon is responding a bit slowly?

I'm also reaching out to let you know that I'm working on a similar topic, only as a static library: https://github.com/beaumanvienna/pamanager
I thought there aren't many good recourses on C++ solutions about how to deal with libpulse and also found your project way too late. I put a link to pamixer in the readme :-) If you have the time to look over it, please let me know any feedback. Thanks!

**Comment by cdemoulins** [comment]
Yes i should add a sleep instruction in the loop.

For your project pamanager, why do you want a static library ?
