### ISSUE TITLE
--get-volume and --get-volume-human return non-zero

### ISSUE THREAD

**Issue by mfiano** [cdemoulins/pamixer#44]
The `--get-volume` and `--get-volume-human` switches return 0 only if volume is not 0 and not muted. If they are it exits with 1 (while still returning the string to stdout).

**Comment by cdemoulins** [comment]
Sorry but what is the issue with this ?

**Comment by mfiano** [comment]
If you are using this in a script to retrieve volume values, I'd expect it to return a non-error exit status when it displays the expected value you requested, unless there was an actual error in the process.

**Comment by jirutka** [comment]
I agree with @mfiano, I also find this behaviour unexpected and undesirable.

**Comment by cdemoulins** [comment]
Ok, it's something i don't really care and added a long time ago (https://github.com/cdemoulins/pamixer/commit/696aa78f969135664f941affd6c6fe7aa8b8ed85).

I will revert to the previous behavior : return 0
