### ISSUE TITLE
[Suggestion] Consider replacing Boost.Program_options with some smaller library

### ISSUE THREAD

**Issue by jirutka** [cdemoulins/pamixer#46]
`libboost_program_options.so` is a huge dependency – 448 kiB just for parsing CLI option.

**Comment by cdemoulins** [comment]
Yes i agree but do you have any suggestions to replace the dependency ?

**Comment by jirutka** [comment]
I’m not C++ developer, so I don’t have experience with any C++ libs for parsing CLI options, just plain C. After a brief googling I found [cxxopts](https://github.com/jarro2783/cxxopts) as a possible candidate that supports auto-generated --help message. I already packaged it for Alpine Linux a month ago for some other package.
