### ISSUE TITLE
Add a `--get-default-source` option

### ISSUE THREAD

**Issue by dcaixinha** [cdemoulins/pamixer#52]
Hi! First of all, thanks for `pamixer`, it's a great tool!

I'd like to have a `--get-default-source` option, that would print the name of the default source, similar to what `--get-default-sink` does. What do you think?

**Comment by concatime** [comment]
I was about to ask the same think. I would like `--get-default-source` to show which microphone is used, is it the internal or external one?

**Comment by concatime** [comment]
One question too, how do I set the default source and sink?

**Comment by cdemoulins** [comment]
It's a good idea but i don't have a lot of time currently. But i accept PR.

**Comment by LordTlasT** [comment]
there's already a `--default-source` option that achieves the same effect
`pamixer --default-source --get-volume`

**Comment by LordTlasT** [comment]
there's already a `--default-source` option that achieves the same effect
`pamixer --default-source --get-volume`
