### ISSUE TITLE
pamixer library & callback functions

### ISSUE THREAD

**Issue by lahwaacz** [cdemoulins/pamixer#6]
Since the README says that pamixer can be used as a library, I find it rather strange that the callback functions are declared in [pulseaudio.hh](https://github.com/cdemoulins/pamixer/blob/master/pulseaudio.hh#L42) but defined in [pamixer.cc](https://github.com/cdemoulins/pamixer/blob/master/pamixer.cc#L43). Are they not general enough to be part of the lib?

**Comment by cdemoulins** [comment]
Before the last pull request, it was true.
I have to do some cleaning.
