### ISSUE TITLE
compilation problem in debian wheezy

### ISSUE THREAD

**Issue by dlebrecht** [cdemoulins/pamixer#7]
when i try to compile in debian wheezy:

% make  
                                                        
g++ --std=c++11 -Wall -Werror -Wextra -pedantic   -c -o pulseaudio.o pulseaudio.cc
pulseaudio.cc: In member function ‘void Pulseaudio::set_volume(Device&, pa_volume_t)’:
pulseaudio.cc:140:22: error: ‘UINT32_MAX’ was not declared in this scope
make: *** [pulseaudio.o] Error 1

these are the specific lines:
140    if (new_volume > PA_VOLUME_MAX) {                                                       
141        new_volume = PA_VOLUME_MAX;                                                         
142    }                                                                                       

if i comment out these lines, compilation works fine

**Comment by cdemoulins** [comment]
gcc 4.7 of debian wheezy doesn't fully support c++11.
